corr: corr.cpp
	g++ -g -std=c++17 -I${BOOST_ROOT}/include corr.cpp -o corr.exe

msd:
	g++ -g -std=c++17 msd.cpp -o msd.exe

h:
	g++ -std=c++17 -I${BOOST_ROOT}/include histogram.cpp -o hist.exe

nbr:
	g++ -std=c++17 nbr.cpp -o nbr.exe

